indicadores_qsd = [
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentração de compostos HPAs",
        "Parametro": "Somatória de HPAs",
        "Unidade": "μg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de arsênio",
        "Parametro": "Arsênio (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de cádmio",
        "Parametro": "Cádmio (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de chumbo",
        "Parametro": "Chumbo (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de cobre",
        "Parametro": "Cobre (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de cromo",
        "Parametro": "Cromo (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de mercúrio",
        "Parametro": "Mercúrio (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de níquel",
        "Parametro": "Níquel (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de zinco",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concentração de nitrogênio",
        "Parametro": "Nitrogênio Kjeldahl Total (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Concetração de fósforo",
        "Parametro": "Fósforo Total (mg/kg)",
        "Unidade": "mg/kg",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Percentual de COT",
        "Parametro": "Carbono Orgânico Total (%)",
        "Unidade": "%",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "ICA",
        "Indicador": "Mortalidade de organismos teste",
        "Parametro": "Mortalidade (%)",
        "Unidade": "%",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº454/2012, por campanha.",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "IDG",
        "Indicador": "Realização de coleta e análise de pontos amostrais",
        "Unidade": "%",
        "Meta": "Realização de coleta e análise em 100% dos pontos amostrais por campanha",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade de Sedimentos",
        "Tipo": "IDG",
        "Indicador": "Realização de campanhas amostrais",
        "Unidade": "%",
        "Meta": "Realização de 100% das campanhas de monitoramento de coleta previstas",
    },
]
