indicadores_qag = [
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de cromo",
        "Parametro": "Cromo total (mg/L Cr)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de mercúrio ",
        "Parametro": "Mercúrio total (mg/L Hg)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de níquel",
        "Parametro": "Níquel total (mg/L Ni)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de nitrato",
        "Parametro": "Nitrato (mg/L NO3)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de nitrito",
        "Parametro": "Nitrito (mg/L NO2)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de nitrogênio amoniacal",
        "Parametro": "Nitrogênio amoniacal (mg/L N-NH4)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de fósforo",
        "Parametro": "Fósforo total (mg/L P)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de COT",
        "Parametro": "Carbono orgânico total (mg/L COT)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de fenóis ",
        "Parametro": "Fenóis totais (mg/L C6H5OH)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de pH",
        "Parametro": "pH",
        "Unidade": "-",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de OD",
        "Parametro": "Oxigênio dissolvido (mg/L O2)",
        "Unidade": "mg/L",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de turbidez",
        "Parametro": "Turbidez (NTU)",
        "Unidade": "NTU",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "ICA",
        "Indicador": "Concentrações/níveis de coliformes totais",
        "Parametro": "Coliformes totais (UFC/100ml)",
        "Unidade": "UFC/100ml",
        "Meta": "Atingir 100% de conformidade com os VMPs definidos na Resolução CONAMA nº 357/2005, por campanha. ",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "IDG",
        "Indicador": "Realização de coleta e análise de pontos amostrais",
        "Parametro": "Pontos amostrais",
        "Unidade": "%",
        "Meta": "Realização de coleta e análise em 100% dos pontos amostrais por campanha",
    },
    {
        "Programa": "Programa de Monitoramento da Qualidade da Água Superficial",
        "Tipo": "IDG",
        "Indicador": "Realização de campanhas amostrais",
        "Parametro": "Campanhas amostrais",
        "Unidade": "%",
        "Meta": "Realização de coleta e análise em 100% dos pontos amostrais por campanha",
    },
]
