{
    "Consumo Humano": {
        "Alumínio": "200 (1)",
        "Antimônio": 5,
        "Arsênio": 10,
        "Bário": 700,
        "Berílio": 4,
        "Boro": "500 (2)",
        "Cádmio": 5,
        "Chumbo": 10,
        "Cianeto": 70,
        "Cloreto": "250.000 (1)",
        "Cobalto": None,
        "Cobre": 2000,
        "Crômio (Cr III + Cr VI)": 50,
        "Ferro": "300 (1)",
        "Fluoreto": 1500,
        "Lítio": None,
        "Manganês": "100 (1)",
        "Mercúrio": 1,
        "Molibdênio": 70,
        "Níquel": "20 (3)",
        "Nitrato (expresso em N)": 10000,
        "Nitrito (expresso em N)": 1000,
        "Prata": 100,
        "Selênio": 10,
        "Sódio": "200.000 (1)",
        "Sólidos Totais Dissolvidos (STD)": "1.000.000 (1)",
        "Sulfato": "250.000 (1)",
        "Urânio": "15 (2,3)",
        "Vanádio": 50,
        "Zinco": "5.000 (1)",
        "Acrilamida": 0.5,
        "Benzeno": 5,
        "Benzo antraceno": 0.05,
        "Benzo fluoranteno": 0.05,
        "Benzo(k)fluoranteno": 0.05,
        "Benzo pireno": 0.05,
        "Cloreto de vinila": 5,
        "Clorofórmio": 200,
        "Criseno": 0.05,
        "1,2-Diclorobenzeno": "1.000 (1)",
        "1,4-Diclorobenzeno": "300 (1)",
        "1,2-Dicloroetano": 10,
        "1,1-Dicloroeteno  (cis + trans)": 30,
        "1,2-Dicloroeteno trans (156-60-5)": None,
        "Dibenzo antraceno": 0.05,
        "Diclorometano": 20,
        "Estireno": 20,
        "Etilbenzeno": "200 (1)",
        "Fenóis  (10)": 3,
        "Indeno(1,2,3)pireno": 0.05,
        "PCBs\n(somatória de 7) (9)": 0.5,
        "Tetracloreto de carbono": 2,
        "Triclorobenzenos (1,2,4-TCB + 1,3,5-\nTCB + 1,2,3)": 20,
        "Tetracloroeteno": 40,
        "1,1,2Tricloroeteno": 70,
        "Tolueno": "170 (*)",
        "Xileno Total (o+m+p)": "300 (*)",
        "Alaclor": 20,
        "Aldicarb + ald. sulfona + ald. sulfóxido": 10,
        "Aldrin + Dieldrin": 0.03,
        "Atrazina": 2,
        "Bentazona": 300,
        "Carbofuran": 7,
        "Clordano (cis + trans)": 0.2,
        "Clorotalonil": 30,
        "Clorpirifós 2,4-D": 30,
        "DDT (p,p’- DDT + p,p’-DDE + p,p’- DDD)": 2,
        "Endosulfan ( I + II + sulfato) II (33213-65-9) sulfato (1031-07-8)": None,
        "Endrin": 0.6,
        "Glifosato + Ampa": 500,
        "Heptacloro epóxido (1024-57-3)": None,
        "Hexaclorobenzeno": 1,
        "Lindano (gama-BHC)": 2,
        "Malation": 190,
        "Metolacloro": 10,
        "Metoxicloro": 20,
        "Molinato": 6,
        "Pendimetalina": 20,
        "Pentaclorofenol": 9,
        "Permetrina": 20,
        "Propanil": 20,
        "Simazina": 2,
        "Trifuralina": 20,
        "E. coli": "Ausentes em 100ml",
        "Enterococos": None,
        "Coliformes termotolerantes": "Ausentes em 100ml",
    },
    "Dessedentação de animais": {
        "Alumínio": 5000,
        "Antimônio": None,
        "Arsênio": 200,
        "Bário": None,
        "Berílio": 100,
        "Boro": 5000,
        "Cádmio": 50,
        "Chumbo": 100,
        "Cianeto": None,
        "Cloreto": None,
        "Cobalto": 1000,
        "Cobre": 500,
        "Crômio (Cr III + Cr VI)": 1000,
        "Ferro": None,
        "Fluoreto": 2000,
        "Lítio": None,
        "Manganês": 50,
        "Mercúrio": 10,
        "Molibdênio": 150,
        "Níquel": 1000,
        "Nitrato (expresso em N)": 90000,
        "Nitrito (expresso em N)": 10000,
        "Prata": None,
        "Selênio": 50,
        "Sódio": None,
        "Sólidos Totais Dissolvidos (STD)": None,
        "Sulfato": 1000000,
        "Urânio": 200,
        "Vanádio": 100,
        "Zinco": 24000,
        "Acrilamida": None,
        "Benzeno": None,
        "Benzo antraceno": None,
        "Benzo fluoranteno": None,
        "Benzo(k)fluoranteno": None,
        "Benzo pireno": None,
        "Cloreto de vinila": None,
        "Clorofórmio": 100,
        "Criseno": None,
        "1,2-Diclorobenzeno": None,
        "1,4-Diclorobenzeno": None,
        "1,2-Dicloroetano": 5,
        "1,1-Dicloroeteno  (cis + trans)": None,
        "1,2-Dicloroeteno trans (156-60-5)": None,
        "Dibenzo antraceno": None,
        "Diclorometano": 50,
        "Estireno": None,
        "Etilbenzeno": None,
        "Fenóis  (10)": 2,
        "Indeno(1,2,3)pireno": None,
        "PCBs\n(somatória de 7) (9)": None,
        "Tetracloreto de carbono": 5,
        "Triclorobenzenos (1,2,4-TCB + 1,3,5-\nTCB + 1,2,3)": None,
        "Tetracloroeteno": None,
        "1,1,2Tricloroeteno": 50,
        "Tolueno": 24,
        "Xileno Total (o+m+p)": None,
        "Alaclor": None,
        "Aldicarb + ald. sulfona + ald. sulfóxido": 11,
        "Aldrin + Dieldrin": None,
        "Atrazina": 5,
        "Bentazona": None,
        "Carbofuran": 45,
        "Clordano (cis + trans)": None,
        "Clorotalonil": 170,
        "Clorpirifós 2,4-D": 24,
        "DDT (p,p’- DDT + p,p’-DDE + p,p’- DDD)": None,
        "Endosulfan ( I + II + sulfato) II (33213-65-9) sulfato (1031-07-8)": None,
        "Endrin": None,
        "Glifosato + Ampa": 280,
        "Heptacloro epóxido (1024-57-3)": None,
        "Hexaclorobenzeno": 0.52,
        "Lindano (gama-BHC)": 4,
        "Malation": None,
        "Metolacloro": 50,
        "Metoxicloro": None,
        "Molinato": None,
        "Pendimetalina": None,
        "Pentaclorofenol": None,
        "Permetrina": None,
        "Propanil": None,
        "Simazina": 10,
        "Trifuralina": 45,
        "E. coli": "200/100 ml",
        "Enterococos": None,
        "Coliformes termotolerantes": "200/100 ml",
    },
    "Irrigação": {
        "Alumínio": 5000,
        "Antimônio": None,
        "Arsênio": None,
        "Bário": None,
        "Berílio": 100,
        "Boro": "500 (4)",
        "Cádmio": 10,
        "Chumbo": 5000,
        "Cianeto": None,
        "Cloreto": "100.000 - 700.000",
        "Cobalto": 50,
        "Cobre": 200,
        "Crômio (Cr III + Cr VI)": 100,
        "Ferro": 5000,
        "Fluoreto": 1000,
        "Lítio": 2500,
        "Manganês": 200,
        "Mercúrio": 2,
        "Molibdênio": 10,
        "Níquel": 200,
        "Nitrato (expresso em N)": None,
        "Nitrito (expresso em N)": 1000,
        "Prata": None,
        "Selênio": 20,
        "Sódio": None,
        "Sólidos Totais Dissolvidos (STD)": None,
        "Sulfato": None,
        "Urânio": "10 (4)",
        "Vanádio": 100,
        "Zinco": 2000,
        "Acrilamida": None,
        "Benzeno": None,
        "Benzo antraceno": None,
        "Benzo fluoranteno": None,
        "Benzo(k)fluoranteno": None,
        "Benzo pireno": None,
        "Cloreto de vinila": None,
        "Clorofórmio": None,
        "Criseno": None,
        "1,2-Diclorobenzeno": None,
        "1,4-Diclorobenzeno": None,
        "1,2-Dicloroetano": None,
        "1,1-Dicloroeteno  (cis + trans)": None,
        "1,2-Dicloroeteno trans (156-60-5)": None,
        "Dibenzo antraceno": None,
        "Diclorometano": None,
        "Estireno": None,
        "Etilbenzeno": None,
        "Fenóis  (10)": None,
        "Indeno(1,2,3)pireno": None,
        "PCBs\n(somatória de 7) (9)": None,
        "Tetracloreto de carbono": None,
        "Triclorobenzenos (1,2,4-TCB + 1,3,5-\nTCB + 1,2,3)": None,
        "Tetracloroeteno": None,
        "1,1,2Tricloroeteno": None,
        "Tolueno": None,
        "Xileno Total (o+m+p)": None,
        "Alaclor": None,
        "Aldicarb + ald. sulfona + ald. sulfóxido": 54.9,
        "Aldrin + Dieldrin": None,
        "Atrazina": 10,
        "Bentazona": None,
        "Carbofuran": None,
        "Clordano (cis + trans)": None,
        "Clorotalonil": 5.8,
        "Clorpirifós 2,4-D": None,
        "DDT (p,p’- DDT + p,p’-DDE + p,p’- DDD)": None,
        "Endosulfan ( I + II + sulfato) II (33213-65-9) sulfato (1031-07-8)": None,
        "Endrin": None,
        "Glifosato + Ampa": "0,13 (6); 0,06 (7); 0,04 (8)",
        "Heptacloro epóxido (1024-57-3)": 3,
        "Hexaclorobenzeno": None,
        "Lindano (gama-BHC)": None,
        "Malation": None,
        "Metolacloro": 28,
        "Metoxicloro": None,
        "Molinato": None,
        "Pendimetalina": None,
        "Pentaclorofenol": None,
        "Permetrina": None,
        "Propanil": None,
        "Simazina": 0.5,
        "Trifuralina": None,
        "E. coli": None,
        "Enterococos": None,
        "Coliformes termotolerantes": None,
    },
    "Recreação": {
        "Alumínio": 200,
        "Antimônio": None,
        "Arsênio": 50,
        "Bário": 1000,
        "Berílio": None,
        "Boro": 1000,
        "Cádmio": 5,
        "Chumbo": 50,
        "Cianeto": 100,
        "Cloreto": 400000,
        "Cobalto": None,
        "Cobre": 1000,
        "Crômio (Cr III + Cr VI)": 50,
        "Ferro": 300,
        "Fluoreto": None,
        "Lítio": None,
        "Manganês": 100,
        "Mercúrio": 1,
        "Molibdênio": None,
        "Níquel": 100,
        "Nitrato (expresso em N)": 10000,
        "Nitrito (expresso em N)": 1000,
        "Prata": 50,
        "Selênio": 10,
        "Sódio": 300000,
        "Sólidos Totais Dissolvidos (STD)": None,
        "Sulfato": 400000,
        "Urânio": None,
        "Vanádio": None,
        "Zinco": 5000,
        "Acrilamida": None,
        "Benzeno": 10,
        "Benzo antraceno": None,
        "Benzo fluoranteno": None,
        "Benzo(k)fluoranteno": None,
        "Benzo pireno": 0.01,
        "Cloreto de vinila": None,
        "Clorofórmio": None,
        "Criseno": None,
        "1,2-Diclorobenzeno": None,
        "1,4-Diclorobenzeno": None,
        "1,2-Dicloroetano": 10,
        "1,1-Dicloroeteno  (cis + trans)": 0.3,
        "1,2-Dicloroeteno trans (156-60-5)": None,
        "Dibenzo antraceno": None,
        "Diclorometano": None,
        "Estireno": None,
        "Etilbenzeno": None,
        "Fenóis  (10)": 2,
        "Indeno(1,2,3)pireno": None,
        "PCBs\n(somatória de 7) (9)": 0.1,
        "Tetracloreto de carbono": 3,
        "Triclorobenzenos (1,2,4-TCB + 1,3,5-\nTCB + 1,2,3)": None,
        "Tetracloroeteno": 10,
        "1,1,2Tricloroeteno": 30,
        "Tolueno": None,
        "Xileno Total (o+m+p)": None,
        "Alaclor": 3,
        "Aldicarb + ald. sulfona + ald. sulfóxido": None,
        "Aldrin + Dieldrin": 1,
        "Atrazina": None,
        "Bentazona": 400,
        "Carbofuran": 30,
        "Clordano (cis + trans)": 6,
        "Clorotalonil": None,
        "Clorpirifós 2,4-D": 100,
        "DDT (p,p’- DDT + p,p’-DDE + p,p’- DDD)": 3,
        "Endosulfan ( I + II + sulfato) II (33213-65-9) sulfato (1031-07-8)": None,
        "Endrin": 1,
        "Glifosato + Ampa": 200,
        "Heptacloro epóxido (1024-57-3)": "0,01 para cada",
        "Hexaclorobenzeno": None,
        "Lindano (gama-BHC)": 10,
        "Malation": None,
        "Metolacloro": 800,
        "Metoxicloro": None,
        "Molinato": 1,
        "Pendimetalina": 600,
        "Pentaclorofenol": 10,
        "Permetrina": 300,
        "Propanil": 1000,
        "Simazina": None,
        "Trifuralina": 500,
        "E. coli": "800/100mL",
        "Enterococos": "100/100mL",
        "Coliformes termotolerantes": "1000/100mL",
    },
    "Limites de quantificação praticáveis (LQP)": {
        "Alumínio": 50,
        "Antimônio": 5,
        "Arsênio": 8,
        "Bário": 20,
        "Berílio": 4,
        "Boro": 200,
        "Cádmio": 5,
        "Chumbo": 10,
        "Cianeto": 50,
        "Cloreto": 2000,
        "Cobalto": 10,
        "Cobre": 50,
        "Crômio (Cr III + Cr VI)": 10,
        "Ferro": 100,
        "Fluoreto": 500,
        "Lítio": 100,
        "Manganês": 25,
        "Mercúrio": 1,
        "Molibdênio": 10,
        "Níquel": 10,
        "Nitrato (expresso em N)": 300,
        "Nitrito (expresso em N)": 20,
        "Prata": 10,
        "Selênio": 10,
        "Sódio": 1000,
        "Sólidos Totais Dissolvidos (STD)": 2000,
        "Sulfato": 5000,
        "Urânio": None,
        "Vanádio": 20,
        "Zinco": 100,
        "Acrilamida": 0.15,
        "Benzeno": 2,
        "Benzo antraceno": 0.15,
        "Benzo fluoranteno": 0.15,
        "Benzo(k)fluoranteno": 0.15,
        "Benzo pireno": 0.15,
        "Cloreto de vinila": 2,
        "Clorofórmio": 5,
        "Criseno": 0.15,
        "1,2-Diclorobenzeno": 5,
        "1,4-Diclorobenzeno": 5,
        "1,2-Dicloroetano": 5,
        "1,1-Dicloroeteno  (cis + trans)": 5,
        "1,2-Dicloroeteno trans (156-60-5)": None,
        "Dibenzo antraceno": 0.15,
        "Diclorometano": 10,
        "Estireno": 5,
        "Etilbenzeno": 5,
        "Fenóis  (10)": 10,
        "Indeno(1,2,3)pireno": 0.15,
        "PCBs\n(somatória de 7) (9)": "0,01 para cada",
        "Tetracloreto de carbono": 2,
        "Triclorobenzenos (1,2,4-TCB + 1,3,5-\nTCB + 1,2,3)": "5 para cada",
        "Tetracloroeteno": 5,
        "1,1,2Tricloroeteno": 5,
        "Tolueno": 5,
        "Xileno Total (o+m+p)": "5 para cada",
        "Alaclor": 0.1,
        "Aldicarb + ald. sulfona + ald. sulfóxido": "3 para cada",
        "Aldrin + Dieldrin": "0,005 para cada",
        "Atrazina": 0.5,
        "Bentazona": 30,
        "Carbofuran": 5,
        "Clordano (cis + trans)": "0,01 para cada",
        "Clorotalonil": 0.1,
        "Clorpirifós 2,4-D": 2,
        "DDT (p,p’- DDT + p,p’-DDE + p,p’- DDD)": "0,01 para cada",
        "Endosulfan ( I + II + sulfato) II (33213-65-9) sulfato (1031-07-8)": None,
        "Endrin": 0.01,
        "Glifosato + Ampa": 30,
        "Heptacloro epóxido (1024-57-3)": None,
        "Hexaclorobenzeno": 0.01,
        "Lindano (gama-BHC)": 0.01,
        "Malation": 2,
        "Metolacloro": 0.1,
        "Metoxicloro": 0.1,
        "Molinato": 5,
        "Pendimetalina": 0.1,
        "Pentaclorofenol": 2,
        "Permetrina": 10,
        "Propanil": 10,
        "Simazina": 1,
        "Trifuralina": 0.1,
        "E. coli": "--",
        "Enterococos": "--",
        "Coliformes termotolerantes": "--",
    },
}
