vmp_qsd = {
    "Águas Doces - Nível 1": {
        "Arsênio (mg/kg)": 5.9,
        "Cadmio (mg/kg)": 0.6,
        "Chumbo (mg/kg)": 35.0,
        "Cobre (mg/kg)": 35.7,
        "Cromo (mg/kg)": 37.3,
        "Mercúrio (mg/kg)": 0.17,
        "Níquel (mg/kg)": 18.0,
        "Zinco (mg/kg)": 123.0,
        "Tributilestanho (μg/kg)": 0,
        "HCH (Alfa HCH) (μg/kg)": 0,
        "HCH (Beta HCH) (μg/kg)": 0,
        "HCH (Delta HCH) (μg/kg)": 0,
        "HCH (Gama HCH/lindano) (μg/kg)": 0.94,
        "Clordano (Alfa) (μg/kg)": 0,
        "Clordano (Gama) (μg/kg)": 0,
        "DDD (μg/kg)": 3.54,
        "DDE (μg/kg)": 1.42,
        "DDT (μg/kg)": 1.19,
        "Dieldrin (μg/kg)": 2.85,
        "Endrin (μg/kg)": 2.67,
        "Bifenilas Policloradas (μg/kg)": 34.1,
        "Benzo(a)antraceno (μg/kg)": 31.7,
        "Benzo(a)pireno (μg/kg)": 31.9,
        "Criseno (μg/kg)": 57.1,
        "Dibenzo(a,h)antraceno (μg/kg)": 6.22,
        "Acenafteno (μg/kg)": 6.71,
        "Acenaftileno (μg/kg)": 5.87,
        "Antraceno (μg/kg)": 46.9,
        "Fenantreno (μg/kg)": 41.9,
        "Fluoranteno (μg/kg)": 111.0,
        "Fluoreno (μg/kg)": 21.2,
        "2-Metilnaftaleno (μg/kg)": 20.2,
        "Naftaleno (μg/kg)": 34.6,
        "Pireno (μg/kg)": 53.0,
        "Somátoria de HPAs (μg/kg)": 1000.0,
        "Carbono Orgânico Total (%)": 10.0,
        "Nitrogênio Kjeldahl Total (mg/kg)": 4800.0,
        "Fósforo Total (mg/kg)": 2000.0,
        "Mortalidade (%)": 50.0,
        "Amônia não ionizada (mg/L)": 0.2,
    },
    "Águas Doces - Nível 2": {
        "Arsênio (mg/kg)": 17.0,
        "Cadmio (mg/kg)": 3.5,
        "Chumbo (mg/kg)": 91.3,
        "Cobre (mg/kg)": 197.0,
        "Cromo (mg/kg)": 90.0,
        "Mercúrio (mg/kg)": 0.486,
        "Níquel (mg/kg)": 35.9,
        "Zinco (mg/kg)": 315.0,
        "Tributilestanho (μg/kg)": 0,
        "HCH (Alfa HCH) (μg/kg)": 0,
        "HCH (Beta HCH) (μg/kg)": 0,
        "HCH (Delta HCH) (μg/kg)": 0,
        "HCH (Gama HCH/lindano) (μg/kg)": 1.38,
        "Clordano (Alfa) (μg/kg)": 0,
        "Clordano (Gama) (μg/kg)": 0,
        "DDD (μg/kg)": 8.51,
        "DDE (μg/kg)": 6.75,
        "DDT (μg/kg)": 4.77,
        "Dieldrin (μg/kg)": 6.67,
        "Endrin (μg/kg)": 62.4,
        "Bifenilas Policloradas (μg/kg)": 277.0,
        "Benzo(a)antraceno (μg/kg)": 385.0,
        "Benzo(a)pireno (μg/kg)": 782.0,
        "Criseno (μg/kg)": 862.0,
        "Dibenzo(a,h)antraceno (μg/kg)": 135.0,
        "Acenafteno (μg/kg)": 88.9,
        "Acenaftileno (μg/kg)": 128.0,
        "Antraceno (μg/kg)": 245.0,
        "Fenantreno (μg/kg)": 515.0,
        "Fluoranteno (μg/kg)": 2355.0,
        "Fluoreno (μg/kg)": 144.0,
        "2-Metilnaftaleno (μg/kg)": 201.0,
        "Naftaleno (μg/kg)": 391.0,
        "Pireno (μg/kg)": 875.0,
        "Somátoria de HPAs (μg/kg)": 0,
        "Carbono Orgânico Total (%)": 10.0,
        "Nitrogênio Kjeldahl Total (mg/kg)": 4800.0,
        "Fósforo Total (mg/kg)": 2000.0,
        "Mortalidade (%)": 50.0,
        "Amônia não ionizada (mg/L)": 0.2,
    },
    "Águas Salinas/Salobras - Nível 1": {
        "Arsênio (mg/kg)": 19.0,
        "Cadmio (mg/kg)": 1.2,
        "Chumbo (mg/kg)": 46.7,
        "Cobre (mg/kg)": 34.0,
        "Cromo (mg/kg)": 81.0,
        "Mercúrio (mg/kg)": 0.3,
        "Níquel (mg/kg)": 20.9,
        "Zinco (mg/kg)": 150.0,
        "Tributilestanho (μg/kg)": 100.0,
        "HCH (Alfa HCH) (μg/kg)": 0.32,
        "HCH (Beta HCH) (μg/kg)": 0.32,
        "HCH (Delta HCH) (μg/kg)": 0.32,
        "HCH (Gama HCH/lindano) (μg/kg)": 0.32,
        "Clordano (Alfa) (μg/kg)": 2.26,
        "Clordano (Gama) (μg/kg)": 2.26,
        "DDD (μg/kg)": 1.22,
        "DDE (μg/kg)": 2.07,
        "DDT (μg/kg)": 1.19,
        "Dieldrin (μg/kg)": 0.71,
        "Endrin (μg/kg)": 2.67,
        "Bifenilas Policloradas (μg/kg)": 22.7,
        "Benzo(a)antraceno (μg/kg)": 280.0,
        "Benzo(a)pireno (μg/kg)": 230.0,
        "Criseno (μg/kg)": 300.0,
        "Dibenzo(a,h)antraceno (μg/kg)": 43.0,
        "Acenafteno (μg/kg)": 16.0,
        "Acenaftileno (μg/kg)": 44.0,
        "Antraceno (μg/kg)": 85.3,
        "Fenantreno (μg/kg)": 240.0,
        "Fluoranteno (μg/kg)": 600.0,
        "Fluoreno (μg/kg)": 19.0,
        "2-Metilnaftaleno (μg/kg)": 70.0,
        "Naftaleno (μg/kg)": 160.0,
        "Pireno (μg/kg)": 665.0,
        "Somátoria de HPAs (μg/kg)": 4000.0,
        "Carbono Orgânico Total (%)": 10.0,
        "Nitrogênio Kjeldahl Total (mg/kg)": 4800.0,
        "Fósforo Total (mg/kg)": 2000.0,
        "Mortalidade (%)": 50.0,
        "Amônia não ionizada (mg/L)": 0.2,
    },
    "Águas Salinas/Salobras - Nível 2": {
        "Arsênio (mg/kg)": 70.0,
        "Cadmio (mg/kg)": 7.2,
        "Chumbo (mg/kg)": 218.0,
        "Cobre (mg/kg)": 270.0,
        "Cromo (mg/kg)": 370.0,
        "Mercúrio (mg/kg)": 1.0,
        "Níquel (mg/kg)": 51.6,
        "Zinco (mg/kg)": 410.0,
        "Tributilestanho (μg/kg)": 1000.0,
        "HCH (Alfa HCH) (μg/kg)": 0.99,
        "HCH (Beta HCH) (μg/kg)": 0.99,
        "HCH (Delta HCH) (μg/kg)": 0.99,
        "HCH (Gama HCH/lindano) (μg/kg)": 0.99,
        "Clordano (Alfa) (μg/kg)": 4.79,
        "Clordano (Gama) (μg/kg)": 4.79,
        "DDD (μg/kg)": 7.81,
        "DDE (μg/kg)": 374.0,
        "DDT (μg/kg)": 4.77,
        "Dieldrin (μg/kg)": 4.3,
        "Endrin (μg/kg)": 62.4,
        "Bifenilas Policloradas (μg/kg)": 180.0,
        "Benzo(a)antraceno (μg/kg)": 690.0,
        "Benzo(a)pireno (μg/kg)": 760.0,
        "Criseno (μg/kg)": 850.0,
        "Dibenzo(a,h)antraceno (μg/kg)": 140.0,
        "Acenafteno (μg/kg)": 500.0,
        "Acenaftileno (μg/kg)": 640.0,
        "Antraceno (μg/kg)": 1100.0,
        "Fenantreno (μg/kg)": 1500.0,
        "Fluoranteno (μg/kg)": 5100.0,
        "Fluoreno (μg/kg)": 540.0,
        "2-Metilnaftaleno (μg/kg)": 670.0,
        "Naftaleno (μg/kg)": 2100.0,
        "Pireno (μg/kg)": 2600.0,
        "Somátoria de HPAs (μg/kg)": 0.0,
        "Carbono Orgânico Total (%)": 10.0,
        "Nitrogênio Kjeldahl Total (mg/kg)": 4800.0,
        "Fósforo Total (mg/kg)": 2000.0,
        "Mortalidade (%)": 50.0,
        "Amônia não ionizada (mg/L)": 0.2,
    },
}
