vmp_qag = {
    "Águas Doces - Nível 1": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": "Virtualmente ausentes",
        "Corantes provenientes de fontes antrópicas": "Virtualmente ausentes",
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "200 col/100mL",
        "DBO 5 dias a 20°C (mg/L O2)": 3,
        "OD (mg/L O2)": 6,
        "Turbidez (UNT)": 40,
        "Cor verdadeira (mg Pt/L)": "Nível de cor natural",
        "pH (N/A)": "6,0 a 9,0",
        "Clorofila a (μg/L)": 10,
        "Densidade de cianobactérias (cel/mL)": 20000,
        "Sólidos dissolvidos totais (mg/L)": 500,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": 0.005,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": 0.7,
        "Berílio total (mg/L Be)": 0.04,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.001,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.005,
        "Cloreto total (mg/L Cl)": 250,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": 0.05,
        "Cobre dissolvido (mg/L Cu)": 0.009,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": 0.02,
        "Fósforo total (ambiente intermediário) (mg/L P)": 0.025,
        "Fósforo total (ambiente lótico) (mg/L P)": 0.1,
        "Lítio total (mg/L Li)": 2.5,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 10,
        "Nitrito (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": 3.7,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": 2,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": 0.5,
        "Prata total (mg/L Ag)": 0.01,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": 250,
        "Sulfeto (H2S não dissociado) (mg/L S)": 0.002,
        "Urânio total (mg/L U)": 0.02,
        "Vanádio total (mg/L V)": 0.1,
        "Zinco total (mg/L Zn)": 0.18,
        "Acrilamida (μg/L)": 0.5,
        "Alacloro (μg/L)": 20,
        "Aldrin + Dieldrin (μg/L)": 0.005,
        "Atrazina (μg/L)": 2,
        "Benzeno (mg/L)": 0.005,
        "Benzidina (μg/L)": 0.001,
        "Benzo (a) antraceno (μg/L)": 0.05,
        "Benzo (a) pireno (μg/L)": 0.05,
        "Benzo(b) fluoranteno (μg/L)": 0.05,
        "Benzo(k) fluoranteno (μg/L)": 0.05,
        "Carbaril (μg/L)": 0.02,
        "Clordano (cis + trans) (μg/L)": 0.04,
        "2-Clorofenol (μg/L)": 0.1,
        "Criseno (μg/L)": 0.05,
        "2,4-D (μg/L)": 4,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": 0.1,
        "Dibenzo (a,h) antraceno (μg/L)": 0.05,
        "1,2-Dicloroetano (mg/L)": 0.01,
        "1,1-Dicloroeteno (mg/L)": 0.003,
        "2,4-Diclorofenol (μg/L)": 0.3,
        "Diclorometano (mg/L)": 0.02,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 0.002,
        "Dodecacloro pentaciclodecano (μg/L)": 0.001,
        "Endossulfan (a + b + sulfato) (μg/L)": 0.056,
        "Endrin (μg/L)": 0.004,
        "Estireno (mg/L)": 0.02,
        "Etilbenzeno (μg/L)": 90,
        "Fenóis totais (mg/L)": 0.5,
        "2,4,5-T (μg/L)": 2,
        "Tetracloreto de carbono (mg/L)": 0.002,
        "Tetracloroeteno (mg/L)": 0.01,
        "Tolueno (μg/L)": 2,
        "Toxafeno (μg/L)": 0.01,
        "2,4,5-TP (μg/L)": 10,
        "Tributilestanho (μg/L)": 0.063,
        "Triclorobenzeno (mg/L)": 0.02,
        "Tricloroeteno (mg/L)": 0.03,
        "2,4,6 - Triclorofenol (mg/L)": 0.01,
        "Trifluralina (μg/L)": 0.2,
        "Xileno": 300,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": None,
        "Carbono orgânico total": None,
        "Fósforo Total": None,
        "Nitrogênio amoniacal total": None,
        "Polifosfatos": None,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": None,
        "Sulfetos (como H2S não dissociado)": "-",
    },
    "Águas Doces - Nível 2": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": "Virtualmente ausentes",
        "Corantes provenientes de fontes antrópicas": "Removíveis por processos convencionais",
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "1000 col/100mL",
        "DBO 5 dias a 20°C (mg/L O2)": 5,
        "OD (mg/L O2)": 5,
        "Turbidez (UNT)": 100,
        "Cor verdadeira (mg Pt/L)": 75,
        "pH (N/A)": "6,0 a 9,0",
        "Clorofila a (μg/L)": 30,
        "Densidade de cianobactérias (cel/mL)": 50000,
        "Sólidos dissolvidos totais (mg/L)": 500,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": 0.005,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": 0.7,
        "Berílio total (mg/L Be)": 0.04,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.001,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.005,
        "Cloreto total (mg/L Cl)": 250,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": 0.05,
        "Cobre dissolvido (mg/L Cu)": 0.009,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": 0.03,
        "Fósforo total (ambiente intermediário) (mg/L P)": 0.05,
        "Fósforo total (ambiente lótico) (mg/L P)": 0.1,
        "Lítio total (mg/L Li)": 2.5,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 10,
        "Nitrito (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": 3.7,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": 2,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": 0.5,
        "Prata total (mg/L Ag)": 0.01,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": 250,
        "Sulfeto (H2S não dissociado) (mg/L S)": 0.002,
        "Urânio total (mg/L U)": 0.02,
        "Vanádio total (mg/L V)": 0.1,
        "Zinco total (mg/L Zn)": 0.18,
        "Acrilamida (μg/L)": 0.5,
        "Alacloro (μg/L)": 20,
        "Aldrin + Dieldrin (μg/L)": 0.005,
        "Atrazina (μg/L)": 2,
        "Benzeno (mg/L)": 0.005,
        "Benzidina (μg/L)": 0.001,
        "Benzo (a) antraceno (μg/L)": 0.05,
        "Benzo (a) pireno (μg/L)": 0.05,
        "Benzo(b) fluoranteno (μg/L)": 0.05,
        "Benzo(k) fluoranteno (μg/L)": 0.05,
        "Carbaril (μg/L)": 0.02,
        "Clordano (cis + trans) (μg/L)": 0.04,
        "2-Clorofenol (μg/L)": 0.1,
        "Criseno (μg/L)": 0.05,
        "2,4-D (μg/L)": 4,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": 0.1,
        "Dibenzo (a,h) antraceno (μg/L)": 0.05,
        "1,2-Dicloroetano (mg/L)": 0.01,
        "1,1-Dicloroeteno (mg/L)": 0.003,
        "2,4-Diclorofenol (μg/L)": 0.3,
        "Diclorometano (mg/L)": 0.02,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 0.002,
        "Dodecacloro pentaciclodecano (μg/L)": 0.001,
        "Endossulfan (a + b + sulfato) (μg/L)": 0.056,
        "Endrin (μg/L)": 0.004,
        "Estireno (mg/L)": 0.02,
        "Etilbenzeno (μg/L)": 90,
        "Fenóis totais (mg/L)": 0.5,
        "2,4,5-T (μg/L)": 2,
        "Tetracloreto de carbono (mg/L)": 0.002,
        "Tetracloroeteno (mg/L)": 0.01,
        "Tolueno (μg/L)": 2,
        "Toxafeno (μg/L)": 0.01,
        "2,4,5-TP (μg/L)": 10,
        "Tributilestanho (μg/L)": 0.063,
        "Triclorobenzeno (mg/L)": 0.02,
        "Tricloroeteno (mg/L)": 0.03,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": 0.2,
        "Xileno": 300,
        "2 , 4 , 6 - Triclorofenol": 0.01,
        "Substâncias que produzem odor e turbidez": None,
        "Carbono orgânico total": None,
        "Fósforo Total": None,
        "Nitrogênio amoniacal total": None,
        "Polifosfatos": None,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": None,
        "Sulfetos (como H2S não dissociado)": "-",
    },
    "Águas Doces - Nível 3": {
        "Não verificação de efeito tóxico crônico": "Não verificação de efeito tóxico agudo",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": "Virtualmente ausentes",
        "Corantes provenientes de fontes antrópicas": "Removíveis por processos convencionais",
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "2500 col/100mL para recreação, 1000 col/100mL para dessedentação, 4000 col/100mL para demais usos",
        "DBO 5 dias a 20°C (mg/L O2)": 10,
        "OD (mg/L O2)": 4,
        "Turbidez (UNT)": 100,
        "Cor verdadeira (mg Pt/L)": 75,
        "pH (N/A)": "6,0 a 9,0",
        "Clorofila a (μg/L)": 60,
        "Densidade de cianobactérias (cel/mL)": 100000,
        "Sólidos dissolvidos totais (mg/L)": 500,
        "Alumínio dissolvido (mg/L Al)": 0.2,
        "Antimônio (mg/L Sb)": 0.005,
        "Arsênio total (mg/L As)": 0.033,
        "Bário total (mg/L Ba)": 1,
        "Berílio total (mg/L Be)": 0.1,
        "Boro total (mg/L B)": 0.75,
        "Cádmio total (mg/L Cd)": 0.01,
        "Chumbo total (mg/L Pb)": 0.033,
        "Cianeto livre (mg/L CN)": 0.022,
        "Cloreto total (mg/L Cl)": 250,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": 0.2,
        "Cobre dissolvido (mg/L Cu)": 0.013,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 5,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": 0.05,
        "Fósforo total (ambiente intermediário) (mg/L P)": 0.075,
        "Fósforo total (ambiente lótico) (mg/L P)": 0.15,
        "Lítio total (mg/L Li)": 2.5,
        "Manganês total (mg/L Mn)": 0.5,
        "Mercúrio total (mg/L Hg)": 0.002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 10,
        "Nitrito (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": 13.3,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": 5.6,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": 2.2,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": 1,
        "Prata total (mg/L Ag)": 0.05,
        "Selênio total (mg/L Se)": 0.05,
        "Sulfato total (mg/L SO4)": 250,
        "Sulfeto (H2S não dissociado) (mg/L S)": 0.3,
        "Urânio total (mg/L U)": 0.02,
        "Vanádio total (mg/L V)": 0.1,
        "Zinco total (mg/L Zn)": 5,
        "Acrilamida (μg/L)": 0.5,
        "Alacloro (μg/L)": 20,
        "Aldrin + Dieldrin (μg/L)": 0.005,
        "Atrazina (μg/L)": 2,
        "Benzeno (mg/L)": 0.005,
        "Benzidina (μg/L)": 0.001,
        "Benzo (a) antraceno (μg/L)": 0.05,
        "Benzo (a) pireno (μg/L)": 0.7,
        "Benzo(b) fluoranteno (μg/L)": 0.05,
        "Benzo(k) fluoranteno (μg/L)": 0.05,
        "Carbaril (μg/L)": 70,
        "Clordano (cis + trans) (μg/L)": 0.3,
        "2-Clorofenol (μg/L)": 0.1,
        "Criseno (μg/L)": 0.05,
        "2,4-D (μg/L)": 30,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": 14,
        "Dibenzo (a,h) antraceno (μg/L)": 0.05,
        "1,2-Dicloroetano (mg/L)": 0.01,
        "1,1-Dicloroeteno (mg/L)": 30,
        "2,4-Diclorofenol (μg/L)": 0.3,
        "Diclorometano (mg/L)": 0.02,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 1,
        "Dodecacloro pentaciclodecano (μg/L)": 0.001,
        "Endossulfan (a + b + sulfato) (μg/L)": 0.22,
        "Endrin (μg/L)": 0.2,
        "Estireno (mg/L)": 0.02,
        "Etilbenzeno (μg/L)": 90,
        "Fenóis totais (mg/L)": 0.01,
        "2,4,5-T (μg/L)": 2,
        "Tetracloreto de carbono (mg/L)": 0.003,
        "Tetracloroeteno (mg/L)": 0.01,
        "Tolueno (μg/L)": 2,
        "Toxafeno (μg/L)": 0.21,
        "2,4,5-TP (μg/L)": 10,
        "Tributilestanho (μg/L)": 2,
        "Triclorobenzeno (mg/L)": 0.02,
        "Tricloroeteno (mg/L)": 0.03,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": 0.2,
        "Xileno": 300,
        "2 , 4 , 6 - Triclorofenol": 0.01,
        "Substâncias que produzem odor e turbidez": None,
        "Carbono orgânico total": None,
        "Fósforo Total": None,
        "Nitrogênio amoniacal total": None,
        "Polifosfatos": None,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": None,
        "Sulfetos (como H2S não dissociado)": "-",
    },
    "Águas Doces - Nível 4": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Toleram-se iridescências",
        "Substâncias que comuniquem gosto ou odor": "Não objetáveis",
        "Corantes provenientes de fontes antrópicas": "Virtualmente ausentes",
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "200 col/100mL",
        "DBO 5 dias a 20°C (mg/L O2)": 3,
        "OD (mg/L O2)": 2,
        "Turbidez (UNT)": 40,
        "Cor verdadeira (mg Pt/L)": "Nível de cor natural",
        "pH (N/A)": "6,0 a 9,0",
        "Clorofila a (μg/L)": 10,
        "Densidade de cianobactérias (cel/mL)": 20000,
        "Sólidos dissolvidos totais (mg/L)": 500,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": 0.005,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": 0.7,
        "Berílio total (mg/L Be)": 0.04,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.001,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.005,
        "Cloreto total (mg/L Cl)": 250,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": 0.05,
        "Cobre dissolvido (mg/L Cu)": 0.009,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": 0.02,
        "Fósforo total (ambiente intermediário) (mg/L P)": 0.025,
        "Fósforo total (ambiente lótico) (mg/L P)": 0.1,
        "Lítio total (mg/L Li)": 2.5,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 10,
        "Nitrito (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": 3.7,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": 2,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": 0.5,
        "Prata total (mg/L Ag)": 0.01,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": 250,
        "Sulfeto (H2S não dissociado) (mg/L S)": 0.002,
        "Urânio total (mg/L U)": 0.02,
        "Vanádio total (mg/L V)": 0.1,
        "Zinco total (mg/L Zn)": 0.18,
        "Acrilamida (μg/L)": None,
        "Alacloro (μg/L)": None,
        "Aldrin + Dieldrin (μg/L)": None,
        "Atrazina (μg/L)": None,
        "Benzeno (mg/L)": None,
        "Benzidina (μg/L)": None,
        "Benzo (a) antraceno (μg/L)": None,
        "Benzo (a) pireno (μg/L)": None,
        "Benzo(b) fluoranteno (μg/L)": None,
        "Benzo(k) fluoranteno (μg/L)": None,
        "Carbaril (μg/L)": None,
        "Clordano (cis + trans) (μg/L)": None,
        "2-Clorofenol (μg/L)": None,
        "Criseno (μg/L)": None,
        "2,4-D (μg/L)": None,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": None,
        "Dibenzo (a,h) antraceno (μg/L)": None,
        "1,2-Dicloroetano (mg/L)": None,
        "1,1-Dicloroeteno (mg/L)": None,
        "2,4-Diclorofenol (μg/L)": None,
        "Diclorometano (mg/L)": None,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": None,
        "Dodecacloro pentaciclodecano (μg/L)": None,
        "Endossulfan (a + b + sulfato) (μg/L)": None,
        "Endrin (μg/L)": None,
        "Estireno (mg/L)": None,
        "Etilbenzeno (μg/L)": None,
        "Fenóis totais (mg/L)": 1,
        "2,4,5-T (μg/L)": None,
        "Tetracloreto de carbono (mg/L)": None,
        "Tetracloroeteno (mg/L)": None,
        "Tolueno (μg/L)": None,
        "Toxafeno (μg/L)": None,
        "2,4,5-TP (μg/L)": None,
        "Tributilestanho (μg/L)": None,
        "Triclorobenzeno (mg/L)": None,
        "Tricloroeteno (mg/L)": None,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": None,
        "Xileno": None,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": None,
        "Carbono orgânico total": None,
        "Fósforo Total": None,
        "Nitrogênio amoniacal total": None,
        "Polifosfatos": None,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": None,
        "Sulfetos (como H2S não dissociado)": "-",
    },
    "Águas Salinas - Nível 1": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": None,
        "Corantes provenientes de fontes antrópicas": "Virtualmente ausentes",
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "43 col/100mL média geométrica (cultivo), 1000 col/100mL (outros usos)",
        "DBO 5 dias a 20°C (mg/L O2)": None,
        "OD (mg/L O2)": 6,
        "Turbidez (UNT)": None,
        "Cor verdadeira (mg Pt/L)": None,
        "pH (N/A)": "6,5 a 8,5, não alterar mais de 0,2 unidades",
        "Clorofila a (μg/L)": None,
        "Densidade de cianobactérias (cel/mL)": None,
        "Sólidos dissolvidos totais (mg/L)": None,
        "Alumínio dissolvido (mg/L Al)": 1.5,
        "Antimônio (mg/L Sb)": None,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": 1,
        "Berílio total (mg/L Be)": 5.3,
        "Boro total (mg/L B)": 5,
        "Cádmio total (mg/L Cd)": 0.005,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.001,
        "Cloreto total (mg/L Cl)": None,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": None,
        "Cobre dissolvido (mg/L Cu)": 0.005,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": None,
        "Fósforo total (ambiente intermediário) (mg/L P)": None,
        "Fósforo total (ambiente lótico) (mg/L P)": None,
        "Lítio total (mg/L Li)": None,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 0.4,
        "Nitrito (mg/L N)": 0.07,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": None,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": None,
        "Prata total (mg/L Ag)": 0.005,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": None,
        "Sulfeto (H2S não dissociado) (mg/L S)": None,
        "Urânio total (mg/L U)": 0.5,
        "Vanádio total (mg/L V)": None,
        "Zinco total (mg/L Zn)": 0.09,
        "Acrilamida (μg/L)": None,
        "Alacloro (μg/L)": None,
        "Aldrin + Dieldrin (μg/L)": 0.0019,
        "Atrazina (μg/L)": None,
        "Benzeno (mg/L)": 700,
        "Benzidina (μg/L)": None,
        "Benzo (a) antraceno (μg/L)": None,
        "Benzo (a) pireno (μg/L)": None,
        "Benzo(b) fluoranteno (μg/L)": None,
        "Benzo(k) fluoranteno (μg/L)": None,
        "Carbaril (μg/L)": 0.32,
        "Clordano (cis + trans) (μg/L)": 0.004,
        "2-Clorofenol (μg/L)": None,
        "Criseno (μg/L)": None,
        "2,4-D (μg/L)": 30,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": 0.1,
        "Dibenzo (a,h) antraceno (μg/L)": None,
        "1,2-Dicloroetano (mg/L)": None,
        "1,1-Dicloroeteno (mg/L)": None,
        "2,4-Diclorofenol (μg/L)": None,
        "Diclorometano (mg/L)": None,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 0.001,
        "Dodecacloro pentaciclodecano (μg/L)": 0.001,
        "Endossulfan (a + b + sulfato) (μg/L)": 0.01,
        "Endrin (μg/L)": 0.004,
        "Estireno (mg/L)": None,
        "Etilbenzeno (μg/L)": 25,
        "Fenóis totais (mg/L)": 60,
        "2,4,5-T (μg/L)": 10,
        "Tetracloreto de carbono (mg/L)": None,
        "Tetracloroeteno (mg/L)": None,
        "Tolueno (μg/L)": 215,
        "Toxafeno (μg/L)": 0.0002,
        "2,4,5-TP (μg/L)": 10,
        "Tributilestanho (μg/L)": 0.01,
        "Triclorobenzeno (mg/L)": 80,
        "Tricloroeteno (mg/L)": 30,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": None,
        "Xileno": None,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": "Virtualmente ausentes",
        "Carbono orgânico total": 3,
        "Fósforo Total": 0.062,
        "Nitrogênio amoniacal total": 0.4,
        "Polifosfatos": 0.031,
        "Sulfetos (H2S não dissociado)": 0.002,
        "Tálio total": 0.1,
        "Gution": 0.01,
        "Heptacloro epóxido + Heptacloro": 0.001,
        "Lindano (g-HCH)": 0.004,
        "Malation": 0.1,
        "Metoxicloro": 0.03,
        "Monoclorobenzeno": 25,
        "Pentaclorofenol": 7.9,
        "PCBs - Bifenilas Policloradas": 0.03,
        "Substâncias tensoativas que reagem com o azul de metileno": 0.2,
        "Substâncias que produzem cor, odor e turbidez": None,
        "Sulfetos (como H2S não dissociado)": "-",
    },
    "Águas Salinas - Nível 2": {
        "Não verificação de efeito tóxico crônico": "Não verificação de efeito tóxico agudo",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": None,
        "Corantes provenientes de fontes antrópicas": "Virtualmente ausentes",
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "2500 col/100mL",
        "DBO 5 dias a 20°C (mg/L O2)": None,
        "OD (mg/L O2)": 5,
        "Turbidez (UNT)": None,
        "Cor verdadeira (mg Pt/L)": None,
        "pH (N/A)": "6,5 a 8,5",
        "Clorofila a (μg/L)": None,
        "Densidade de cianobactérias (cel/mL)": None,
        "Sólidos dissolvidos totais (mg/L)": None,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": 0.005,
        "Arsênio total (mg/L As)": 0.069,
        "Bário total (mg/L Ba)": 0.7,
        "Berílio total (mg/L Be)": 0.04,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.04,
        "Chumbo total (mg/L Pb)": 0.21,
        "Cianeto livre (mg/L CN)": 0.001,
        "Cloreto total (mg/L Cl)": 250,
        "Cloro residual total (mg/L Cl)": 19,
        "Cobalto total (mg/L Co)": 0.05,
        "Cobre dissolvido (mg/L Cu)": 7.8,
        "Cromo total (mg/L Cr)": 1.1,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": None,
        "Fósforo total (ambiente intermediário) (mg/L P)": None,
        "Fósforo total (ambiente lótico) (mg/L P)": None,
        "Lítio total (mg/L Li)": None,
        "Manganês total (mg/L Mn)": None,
        "Mercúrio total (mg/L Hg)": 1.8,
        "Níquel total (mg/L Ni)": 0.074,
        "Nitrato (mg/L N)": 0.7,
        "Nitrito (mg/L N)": 0.2,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": None,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": None,
        "Prata total (mg/L Ag)": None,
        "Selênio total (mg/L Se)": 0.29,
        "Sulfato total (mg/L SO4)": 250,
        "Sulfeto (H2S não dissociado) (mg/L S)": 0.002,
        "Urânio total (mg/L U)": 0.02,
        "Vanádio total (mg/L V)": 0.1,
        "Zinco total (mg/L Zn)": 0.12,
        "Acrilamida (μg/L)": None,
        "Alacloro (μg/L)": None,
        "Aldrin + Dieldrin (μg/L)": 0.03,
        "Atrazina (μg/L)": None,
        "Benzeno (mg/L)": None,
        "Benzidina (μg/L)": None,
        "Benzo (a) antraceno (μg/L)": None,
        "Benzo (a) pireno (μg/L)": None,
        "Benzo(b) fluoranteno (μg/L)": None,
        "Benzo(k) fluoranteno (μg/L)": None,
        "Carbaril (μg/L)": None,
        "Clordano (cis + trans) (μg/L)": 0.09,
        "2-Clorofenol (μg/L)": None,
        "Criseno (μg/L)": None,
        "2,4-D (μg/L)": None,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": None,
        "Dibenzo (a,h) antraceno (μg/L)": None,
        "1,2-Dicloroetano (mg/L)": None,
        "1,1-Dicloroeteno (mg/L)": None,
        "2,4-Diclorofenol (μg/L)": None,
        "Diclorometano (mg/L)": None,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 0.13,
        "Dodecacloro pentaciclodecano (μg/L)": None,
        "Endossulfan (a + b + sulfato) (μg/L)": None,
        "Endrin (μg/L)": 0.037,
        "Estireno (mg/L)": None,
        "Etilbenzeno (μg/L)": None,
        "Fenóis totais (mg/L)": None,
        "2,4,5-T (μg/L)": None,
        "Tetracloreto de carbono (mg/L)": None,
        "Tetracloroeteno (mg/L)": None,
        "Tolueno (μg/L)": None,
        "Toxafeno (μg/L)": 0.21,
        "2,4,5-TP (μg/L)": None,
        "Tributilestanho (μg/L)": 0.37,
        "Triclorobenzeno (mg/L)": None,
        "Tricloroeteno (mg/L)": None,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": None,
        "Xileno": None,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": "Virtualmente ausentes",
        "Carbono orgânico total": 5,
        "Fósforo Total": 0.093,
        "Nitrogênio amoniacal total": 0.7,
        "Polifosfatos": 0.0465,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": 0.053,
        "Lindano (g-HCH)": 0.16,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": 13,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": None,
        "Sulfetos (como H2S não dissociado)": "-",
    },
    "Águas Salinas - Nível 3": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Toleram-se iridescências",
        "Substâncias que comuniquem gosto ou odor": None,
        "Corantes provenientes de fontes antrópicas": "Virtualmente ausentes",
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "4000 col/100mL",
        "DBO 5 dias a 20°C (mg/L O2)": None,
        "OD (mg/L O2)": 4,
        "Turbidez (UNT)": None,
        "Cor verdadeira (mg Pt/L)": None,
        "pH (N/A)": "6,5 a 8,5, não alterar mais de 0,2 unidades",
        "Clorofila a (μg/L)": None,
        "Densidade de cianobactérias (cel/mL)": None,
        "Sólidos dissolvidos totais (mg/L)": None,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": 0.005,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": 0.7,
        "Berílio total (mg/L Be)": 0.04,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.001,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.005,
        "Cloreto total (mg/L Cl)": 250,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": 0.05,
        "Cobre dissolvido (mg/L Cu)": 0.009,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": 0.02,
        "Fósforo total (ambiente intermediário) (mg/L P)": 0.025,
        "Fósforo total (ambiente lótico) (mg/L P)": 0.1,
        "Lítio total (mg/L Li)": 2.5,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 10,
        "Nitrito (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": 3.7,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": 2,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": 1,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": 0.5,
        "Prata total (mg/L Ag)": 0.01,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": 250,
        "Sulfeto (H2S não dissociado) (mg/L S)": 0.002,
        "Urânio total (mg/L U)": 0.02,
        "Vanádio total (mg/L V)": 0.1,
        "Zinco total (mg/L Zn)": 0.18,
        "Acrilamida (μg/L)": None,
        "Alacloro (μg/L)": None,
        "Aldrin + Dieldrin (μg/L)": None,
        "Atrazina (μg/L)": None,
        "Benzeno (mg/L)": None,
        "Benzidina (μg/L)": None,
        "Benzo (a) antraceno (μg/L)": None,
        "Benzo (a) pireno (μg/L)": None,
        "Benzo(b) fluoranteno (μg/L)": None,
        "Benzo(k) fluoranteno (μg/L)": None,
        "Carbaril (μg/L)": None,
        "Clordano (cis + trans) (μg/L)": None,
        "2-Clorofenol (μg/L)": None,
        "Criseno (μg/L)": None,
        "2,4-D (μg/L)": None,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": None,
        "Dibenzo (a,h) antraceno (μg/L)": None,
        "1,2-Dicloroetano (mg/L)": None,
        "1,1-Dicloroeteno (mg/L)": None,
        "2,4-Diclorofenol (μg/L)": None,
        "Diclorometano (mg/L)": None,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": None,
        "Dodecacloro pentaciclodecano (μg/L)": None,
        "Endossulfan (a + b + sulfato) (μg/L)": None,
        "Endrin (μg/L)": None,
        "Estireno (mg/L)": None,
        "Etilbenzeno (μg/L)": None,
        "Fenóis totais (mg/L)": 1,
        "2,4,5-T (μg/L)": None,
        "Tetracloreto de carbono (mg/L)": None,
        "Tetracloroeteno (mg/L)": None,
        "Tolueno (μg/L)": None,
        "Toxafeno (μg/L)": None,
        "2,4,5-TP (μg/L)": None,
        "Tributilestanho (μg/L)": None,
        "Triclorobenzeno (mg/L)": None,
        "Tricloroeteno (mg/L)": None,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": None,
        "Xileno": None,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": "Virtualmente ausentes",
        "Carbono orgânico total": 10,
        "Fósforo Total": None,
        "Nitrogênio amoniacal total": None,
        "Polifosfatos": None,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": None,
        "Sulfetos (como H2S não dissociado)": "-",
    },
    "Águas Salinas/Salobras - Nível 1": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": None,
        "Corantes provenientes de fontes antrópicas": None,
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "43 col/100mL (cultivo), 200 col/100mL (irrigação), 1000 col/100mL (outros usos)",
        "DBO 5 dias a 20°C (mg/L O2)": None,
        "OD (mg/L O2)": 5,
        "Turbidez (UNT)": None,
        "Cor verdadeira (mg Pt/L)": None,
        "pH (N/A)": "6,5 a 8,5",
        "Clorofila a (μg/L)": None,
        "Densidade de cianobactérias (cel/mL)": None,
        "Sólidos dissolvidos totais (mg/L)": None,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": None,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": None,
        "Berílio total (mg/L Be)": 5.3,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.005,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.001,
        "Cloreto total (mg/L Cl)": None,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": None,
        "Cobre dissolvido (mg/L Cu)": 0.005,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": None,
        "Fósforo total (ambiente intermediário) (mg/L P)": None,
        "Fósforo total (ambiente lótico) (mg/L P)": None,
        "Lítio total (mg/L Li)": None,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 0.4,
        "Nitrito (mg/L N)": 0.07,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": None,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": None,
        "Prata total (mg/L Ag)": 0.005,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": None,
        "Sulfeto (H2S não dissociado) (mg/L S)": None,
        "Urânio total (mg/L U)": None,
        "Vanádio total (mg/L V)": None,
        "Zinco total (mg/L Zn)": 0.09,
        "Acrilamida (μg/L)": None,
        "Alacloro (μg/L)": None,
        "Aldrin + Dieldrin (μg/L)": 0.0019,
        "Atrazina (μg/L)": None,
        "Benzeno (mg/L)": 700,
        "Benzidina (μg/L)": None,
        "Benzo (a) antraceno (μg/L)": None,
        "Benzo (a) pireno (μg/L)": None,
        "Benzo(b) fluoranteno (μg/L)": None,
        "Benzo(k) fluoranteno (μg/L)": None,
        "Carbaril (μg/L)": 0.32,
        "Clordano (cis + trans) (μg/L)": 0.004,
        "2-Clorofenol (μg/L)": None,
        "Criseno (μg/L)": None,
        "2,4-D (μg/L)": 10,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": 0.1,
        "Dibenzo (a,h) antraceno (μg/L)": None,
        "1,2-Dicloroetano (mg/L)": None,
        "1,1-Dicloroeteno (mg/L)": None,
        "2,4-Diclorofenol (μg/L)": None,
        "Diclorometano (mg/L)": None,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 0.001,
        "Dodecacloro pentaciclodecano (μg/L)": 0.001,
        "Endossulfan (a + b + sulfato) (μg/L)": 0.01,
        "Endrin (μg/L)": 0.004,
        "Estireno (mg/L)": None,
        "Etilbenzeno (μg/L)": 25,
        "Fenóis totais (mg/L)": 0.2,
        "2,4,5-T (μg/L)": 10,
        "Tetracloreto de carbono (mg/L)": None,
        "Tetracloroeteno (mg/L)": None,
        "Tolueno (μg/L)": 215,
        "Toxafeno (μg/L)": 0.0002,
        "2,4,5-TP (μg/L)": 10,
        "Tributilestanho (μg/L)": 0.01,
        "Triclorobenzeno (mg/L)": 80,
        "Tricloroeteno (mg/L)": None,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": None,
        "Xileno": None,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": None,
        "Carbono orgânico total": 3,
        "Fósforo Total": 0.124,
        "Nitrogênio amoniacal total": 0.4,
        "Polifosfatos": 0.062,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": "Virtualmente ausentes",
        "Sulfetos (como H2S não dissociado)": 0.002,
    },
    "Águas Salobras - Nível 2": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": None,
        "Corantes provenientes de fontes antrópicas": None,
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "43 col/100mL (cultivo), 200 col/100mL (irrigação), 1000 col/100mL (outros usos)",
        "DBO 5 dias a 20°C (mg/L O2)": None,
        "OD (mg/L O2)": 5,
        "Turbidez (UNT)": None,
        "Cor verdadeira (mg Pt/L)": None,
        "pH (N/A)": "6,5 a 8,5",
        "Clorofila a (μg/L)": None,
        "Densidade de cianobactérias (cel/mL)": None,
        "Sólidos dissolvidos totais (mg/L)": None,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": None,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": None,
        "Berílio total (mg/L Be)": 5.3,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.005,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.001,
        "Cloreto total (mg/L Cl)": None,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": None,
        "Cobre dissolvido (mg/L Cu)": 0.005,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": None,
        "Fósforo total (ambiente intermediário) (mg/L P)": None,
        "Fósforo total (ambiente lótico) (mg/L P)": None,
        "Lítio total (mg/L Li)": None,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 0.4,
        "Nitrito (mg/L N)": 0.07,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": None,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": None,
        "Prata total (mg/L Ag)": 0.005,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": None,
        "Sulfeto (H2S não dissociado) (mg/L S)": None,
        "Urânio total (mg/L U)": None,
        "Vanádio total (mg/L V)": None,
        "Zinco total (mg/L Zn)": 0.09,
        "Acrilamida (μg/L)": None,
        "Alacloro (μg/L)": None,
        "Aldrin + Dieldrin (μg/L)": 0.0019,
        "Atrazina (μg/L)": None,
        "Benzeno (mg/L)": 700,
        "Benzidina (μg/L)": None,
        "Benzo (a) antraceno (μg/L)": None,
        "Benzo (a) pireno (μg/L)": None,
        "Benzo(b) fluoranteno (μg/L)": None,
        "Benzo(k) fluoranteno (μg/L)": None,
        "Carbaril (μg/L)": 0.32,
        "Clordano (cis + trans) (μg/L)": 0.004,
        "2-Clorofenol (μg/L)": None,
        "Criseno (μg/L)": None,
        "2,4-D (μg/L)": 10,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": 0.1,
        "Dibenzo (a,h) antraceno (μg/L)": None,
        "1,2-Dicloroetano (mg/L)": None,
        "1,1-Dicloroeteno (mg/L)": None,
        "2,4-Diclorofenol (μg/L)": None,
        "Diclorometano (mg/L)": None,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 0.001,
        "Dodecacloro pentaciclodecano (μg/L)": 0.001,
        "Endossulfan (a + b + sulfato) (μg/L)": 0.01,
        "Endrin (μg/L)": 0.004,
        "Estireno (mg/L)": None,
        "Etilbenzeno (μg/L)": 25,
        "Fenóis totais (mg/L)": 0.2,
        "2,4,5-T (μg/L)": 10,
        "Tetracloreto de carbono (mg/L)": None,
        "Tetracloroeteno (mg/L)": None,
        "Tolueno (μg/L)": 215,
        "Toxafeno (μg/L)": 0.0002,
        "2,4,5-TP (μg/L)": 10,
        "Tributilestanho (μg/L)": 0.01,
        "Triclorobenzeno (mg/L)": 80,
        "Tricloroeteno (mg/L)": None,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": None,
        "Xileno": None,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": None,
        "Carbono orgânico total": 3,
        "Fósforo Total": 0.124,
        "Nitrogênio amoniacal total": 0.4,
        "Polifosfatos": 0.062,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": "Virtualmente ausentes",
        "Sulfetos (como H2S não dissociado)": 0.002,
    },
    "Águas Salobras - Nível 3": {
        "Não verificação de efeito tóxico crônico": "Conforme critérios de órgão competente",
        "Materiais flutuantes": "Virtualmente ausentes",
        "Óleos e graxas": "Virtualmente ausentes",
        "Substâncias que comuniquem gosto ou odor": None,
        "Corantes provenientes de fontes antrópicas": None,
        "Resíduos sólidos objetáveis": "Virtualmente ausentes",
        "Coliformes termotolerantes (NMP/100mL)": "43 col/100mL (cultivo), 200 col/100mL (irrigação), 1000 col/100mL (outros usos)",
        "DBO 5 dias a 20°C (mg/L O2)": None,
        "OD (mg/L O2)": 5,
        "Turbidez (UNT)": None,
        "Cor verdadeira (mg Pt/L)": None,
        "pH (N/A)": "6,5 a 8,5",
        "Clorofila a (μg/L)": None,
        "Densidade de cianobactérias (cel/mL)": None,
        "Sólidos dissolvidos totais (mg/L)": None,
        "Alumínio dissolvido (mg/L Al)": 0.1,
        "Antimônio (mg/L Sb)": None,
        "Arsênio total (mg/L As)": 0.01,
        "Bário total (mg/L Ba)": None,
        "Berílio total (mg/L Be)": 5.3,
        "Boro total (mg/L B)": 0.5,
        "Cádmio total (mg/L Cd)": 0.005,
        "Chumbo total (mg/L Pb)": 0.01,
        "Cianeto livre (mg/L CN)": 0.001,
        "Cloreto total (mg/L Cl)": None,
        "Cloro residual total (mg/L Cl)": 0.01,
        "Cobalto total (mg/L Co)": None,
        "Cobre dissolvido (mg/L Cu)": 0.005,
        "Cromo total (mg/L Cr)": 0.05,
        "Ferro dissolvido (mg/L Fe)": 0.3,
        "Fluoreto total (mg/L F)": 1.4,
        "Fósforo total (ambiente lêntico) (mg/L P)": None,
        "Fósforo total (ambiente intermediário) (mg/L P)": None,
        "Fósforo total (ambiente lótico) (mg/L P)": None,
        "Lítio total (mg/L Li)": None,
        "Manganês total (mg/L Mn)": 0.1,
        "Mercúrio total (mg/L Hg)": 0.0002,
        "Níquel total (mg/L Ni)": 0.025,
        "Nitrato (mg/L N)": 0.4,
        "Nitrito (mg/L N)": 0.07,
        "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)": None,
        "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)": None,
        "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)": None,
        "Prata total (mg/L Ag)": 0.005,
        "Selênio total (mg/L Se)": 0.01,
        "Sulfato total (mg/L SO4)": None,
        "Sulfeto (H2S não dissociado) (mg/L S)": None,
        "Urânio total (mg/L U)": None,
        "Vanádio total (mg/L V)": None,
        "Zinco total (mg/L Zn)": 0.09,
        "Acrilamida (μg/L)": None,
        "Alacloro (μg/L)": None,
        "Aldrin + Dieldrin (μg/L)": 0.0019,
        "Atrazina (μg/L)": None,
        "Benzeno (mg/L)": 700,
        "Benzidina (μg/L)": None,
        "Benzo (a) antraceno (μg/L)": None,
        "Benzo (a) pireno (μg/L)": None,
        "Benzo(b) fluoranteno (μg/L)": None,
        "Benzo(k) fluoranteno (μg/L)": None,
        "Carbaril (μg/L)": 0.32,
        "Clordano (cis + trans) (μg/L)": 0.004,
        "2-Clorofenol (μg/L)": None,
        "Criseno (μg/L)": None,
        "2,4-D (μg/L)": 10,
        "Demeton (Demeton-O + Demeton-S) (μg/L)": 0.1,
        "Dibenzo (a,h) antraceno (μg/L)": None,
        "1,2-Dicloroetano (mg/L)": None,
        "1,1-Dicloroeteno (mg/L)": None,
        "2,4-Diclorofenol (μg/L)": None,
        "Diclorometano (mg/L)": None,
        "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)": 0.001,
        "Dodecacloro pentaciclodecano (μg/L)": 0.001,
        "Endossulfan (a + b + sulfato) (μg/L)": 0.01,
        "Endrin (μg/L)": 0.004,
        "Estireno (mg/L)": None,
        "Etilbenzeno (μg/L)": 25,
        "Fenóis totais (mg/L)": 0.2,
        "2,4,5-T (μg/L)": 10,
        "Tetracloreto de carbono (mg/L)": None,
        "Tetracloroeteno (mg/L)": None,
        "Tolueno (μg/L)": 215,
        "Toxafeno (μg/L)": 0.0002,
        "2,4,5-TP (μg/L)": 10,
        "Tributilestanho (μg/L)": 0.01,
        "Triclorobenzeno (mg/L)": 80,
        "Tricloroeteno (mg/L)": None,
        "2,4,6 - Triclorofenol (mg/L)": None,
        "Trifluralina (μg/L)": None,
        "Xileno": None,
        "2 , 4 , 6 - Triclorofenol": None,
        "Substâncias que produzem odor e turbidez": None,
        "Carbono orgânico total": 3,
        "Fósforo Total": 0.124,
        "Nitrogênio amoniacal total": 0.4,
        "Polifosfatos": 0.062,
        "Sulfetos (H2S não dissociado)": None,
        "Tálio total": None,
        "Gution": None,
        "Heptacloro epóxido + Heptacloro": None,
        "Lindano (g-HCH)": None,
        "Malation": None,
        "Metoxicloro": None,
        "Monoclorobenzeno": None,
        "Pentaclorofenol": None,
        "PCBs - Bifenilas Policloradas": None,
        "Substâncias tensoativas que reagem com o azul de metileno": None,
        "Substâncias que produzem cor, odor e turbidez": "Virtualmente ausentes",
        "Sulfetos (como H2S não dissociado)": 0.002,
    },
}
